using InfowareSoft.Blazor.MaterialDesign.Components.Base;
using System;
using System.Collections.Generic;
using System.Text;

namespace InfowareSoft.Blazor.MaterialDesign.Components
{
    public enum MDIconEnum
    {
        //action
        [Html("3d_rotation")]
        _3d_rotation,
        [Html("accessibility")]
        accessibility,
        [Html("accessibility_new")]
        accessibility_new,
        [Html("accessible")]
        accessible,
        [Html("accessible_forward")]
        accessible_forward,
        [Html("account_balance")]
        account_balance,
        [Html("account_balance_wallet")]
        account_balance_wallet,
        [Html("account_box")]
        account_box,
        [Html("account_circle")]
        account_circle,
        [Html("add_shopping_cart")]
        add_shopping_cart,
        [Html("alarm")]
        alarm,
        [Html("alarm_add")]
        alarm_add,
        [Html("alarm_off")]
        alarm_off,
        [Html("alarm_on")]
        alarm_on,
        [Html("all_inbox")]
        all_inbox,
        [Html("all_out")]
        all_out,
        [Html("android")]
        android,
        [Html("announcement")]
        announcement,
        [Html("arrow_right_alt")]
        arrow_right_alt,
        [Html("aspect_ratio")]
        aspect_ratio,
        [Html("assessment")]
        assessment,
        [Html("assignment")]
        assignment,
        [Html("assignment_ind")]
        assignment_ind,
        [Html("assignment_late")]
        assignment_late,
        [Html("assignment_return")]
        assignment_return,
        [Html("assignment_returned")]
        assignment_returned,
        [Html("assignment_turned_in")]
        assignment_turned_in,
        [Html("autorenew")]
        autorenew,
        [Html("backup")]
        backup,
        [Html("book")]
        book,
        [Html("bookmark")]
        bookmark,
        [Html("bookmark_border")]
        bookmark_border,
        [Html("bookmarks")]
        bookmarks,
        [Html("bug_report")]
        bug_report,
        [Html("build")]
        build,
        [Html("cached")]
        cached,
        [Html("calendar_today")]
        calendar_today,
        [Html("calendar_view_day")]
        calendar_view_day,
        [Html("camera_enhance")]
        camera_enhance,
        [Html("cancel_schedule_send")]
        cancel_schedule_send,
        [Html("card_giftcard")]
        card_giftcard,
        [Html("card_membership")]
        card_membership,
        [Html("card_travel")]
        card_travel,
        [Html("change_history")]
        change_history,
        [Html("check_circle")]
        check_circle,
        [Html("check_circle_outline")]
        check_circle_outline,
        [Html("chrome_reader_mode")]
        chrome_reader_mode,
        [Html("class")]
        _class,
        [Html("code")]
        code,
        [Html("commute")]
        commute,
        [Html("compare_arrows")]
        compare_arrows,
        [Html("contact_support")]
        contact_support,
        [Html("contactless")]
        contactless,
        [Html("copyright")]
        copyright,
        [Html("credit_card")]
        credit_card,
        [Html("dashboard")]
        dashboard,
        [Html("date_range")]
        date_range,
        [Html("delete")]
        delete,
        [Html("delete_forever")]
        delete_forever,
        [Html("delete_outline")]
        delete_outline,
        [Html("description")]
        description,
        [Html("dns")]
        dns,
        [Html("done")]
        done,
        [Html("done_all")]
        done_all,
        [Html("done_outline")]
        done_outline,
        [Html("donut_large")]
        donut_large,
        [Html("donut_small")]
        donut_small,
        [Html("drag_indicator")]
        drag_indicator,
        [Html("eco")]
        eco,
        [Html("eject")]
        eject,
        [Html("euro_symbol")]
        euro_symbol,
        [Html("event")]
        _event,
        [Html("event_seat")]
        event_seat,
        [Html("exit_to_app")]
        exit_to_app,
        [Html("explore")]
        explore,
        [Html("explore_off")]
        explore_off,
        [Html("extension")]
        extension,
        [Html("face")]
        face,
        [Html("favorite")]
        favorite,
        [Html("favorite_border")]
        favorite_border,
        [Html("feedback")]
        feedback,
        [Html("find_in_page")]
        find_in_page,
        [Html("find_replace")]
        find_replace,
        [Html("fingerprint")]
        fingerprint,
        [Html("flight_land")]
        flight_land,
        [Html("flight_takeoff")]
        flight_takeoff,
        [Html("flip_to_back")]
        flip_to_back,
        [Html("flip_to_front")]
        flip_to_front,
        [Html("g_translate")]
        g_translate,
        [Html("gavel")]
        gavel,
        [Html("get_app")]
        get_app,
        [Html("gif")]
        gif,
        [Html("grade")]
        grade,
        [Html("group_work")]
        group_work,
        [Html("help")]
        help,
        [Html("help_outline")]
        help_outline,
        [Html("highlight_off")]
        highlight_off,
        [Html("history")]
        history,
        [Html("home")]
        home,
        [Html("horizontal_split")]
        horizontal_split,
        [Html("hourglass_empty")]
        hourglass_empty,
        [Html("hourglass_full")]
        hourglass_full,
        [Html("http")]
        http,
        [Html("https")]
        https,
        [Html("important_devices")]
        important_devices,
        [Html("info")]
        info,
        [Html("input")]
        input,
        [Html("invert_colors")]
        invert_colors,
        [Html("label")]
        label,
        [Html("label_important")]
        label_important,
        [Html("label_off")]
        label_off,
        [Html("language")]
        language,
        [Html("launch")]
        launch,
        [Html("line_style")]
        line_style,
        [Html("line_weight")]
        line_weight,
        [Html("list")]
        list,
        [Html("lock")]
        _lock,
        [Html("lock_open")]
        lock_open,
        [Html("loyalty")]
        loyalty,
        [Html("markunread_mailbox")]
        markunread_mailbox,
        [Html("maximize")]
        maximize,
        [Html("minimize")]
        minimize,
        [Html("motorcycle")]
        motorcycle,
        [Html("note_add")]
        note_add,
        [Html("offline_bolt")]
        offline_bolt,
        [Html("offline_pin")]
        offline_pin,
        [Html("opacity")]
        opacity,
        [Html("open_in_browser")]
        open_in_browser,
        [Html("open_in_new")]
        open_in_new,
        [Html("open_with")]
        open_with,
        [Html("pageview")]
        pageview,
        [Html("pan_tool")]
        pan_tool,
        [Html("payment")]
        payment,
        [Html("perm_camera_mic")]
        perm_camera_mic,
        [Html("perm_contact_calendar")]
        perm_contact_calendar,
        [Html("perm_data_setting")]
        perm_data_setting,
        [Html("perm_device_information")]
        perm_device_information,
        [Html("perm_identity")]
        perm_identity,
        [Html("perm_media")]
        perm_media,
        [Html("perm_phone_msg")]
        perm_phone_msg,
        [Html("perm_scan_wifi")]
        perm_scan_wifi,
        [Html("pets")]
        pets,
        [Html("picture_in_picture")]
        picture_in_picture,
        [Html("picture_in_picture_alt")]
        picture_in_picture_alt,
        [Html("play_for_work")]
        play_for_work,
        [Html("polymer")]
        polymer,
        [Html("power_settings_new")]
        power_settings_new,
        [Html("pregnant_woman")]
        pregnant_woman,
        [Html("print")]
        print,
        [Html("query_builder")]
        query_builder,
        [Html("question_answer")]
        question_answer,
        [Html("receipt")]
        receipt,
        [Html("record_voice_over")]
        record_voice_over,
        [Html("redeem")]
        redeem,
        [Html("remove_shopping_cart")]
        remove_shopping_cart,
        [Html("reorder")]
        reorder,
        [Html("report_problem")]
        report_problem,
        [Html("restore")]
        restore,
        [Html("restore_from_trash")]
        restore_from_trash,
        [Html("restore_page")]
        restore_page,
        [Html("room")]
        room,
        [Html("rounded_corner")]
        rounded_corner,
        [Html("rowing")]
        rowing,
        [Html("schedule")]
        schedule,
        [Html("search")]
        search,
        [Html("settings_applications")]
        settings_applications,
        [Html("settings_backup_restore")]
        settings_backup_restore,
        [Html("settings_bluetooth")]
        settings_bluetooth,
        [Html("settings_brightness")]
        settings_brightness,
        [Html("settings_cell")]
        settings_cell,
        [Html("settings_ethernet")]
        settings_ethernet,
        [Html("settings_input_antenna")]
        settings_input_antenna,
        [Html("settings_input_component")]
        settings_input_component,
        [Html("settings_input_composite")]
        settings_input_composite,
        [Html("settings_input_hdmi")]
        settings_input_hdmi,
        [Html("settings_input_svideo")]
        settings_input_svideo,
        [Html("settings_overscan")]
        settings_overscan,
        [Html("settings_phone")]
        settings_phone,
        [Html("settings_power")]
        settings_power,
        [Html("settings_remote")]
        settings_remote,
        [Html("settings_voice")]
        settings_voice,
        [Html("shop")]
        shop,
        [Html("shop_two")]
        shop_two,
        [Html("shopping_basket")]
        shopping_basket,
        [Html("shopping_cart")]
        shopping_cart,
        [Html("speaker_notes")]
        speaker_notes,
        [Html("speaker_notes_off")]
        speaker_notes_off,
        [Html("spellcheck")]
        spellcheck,
        [Html("stars")]
        stars,
        [Html("store")]
        store,
        [Html("subject")]
        subject,
        [Html("supervised_user_circle")]
        supervised_user_circle,
        [Html("supervisor_account")]
        supervisor_account,
        [Html("swap_horiz")]
        swap_horiz,
        [Html("swap_horizontal_circle")]
        swap_horizontal_circle,
        [Html("swap_vert")]
        swap_vert,
        [Html("swap_vertical_circle")]
        swap_vertical_circle,
        [Html("sync_alt")]
        sync_alt,
        [Html("system_update_alt")]
        system_update_alt,
        [Html("tab")]
        tab,
        [Html("tab_unselected")]
        tab_unselected,
        [Html("text_rotate_up")]
        text_rotate_up,
        [Html("text_rotate_vertical")]
        text_rotate_vertical,
        [Html("text_rotation_angledown")]
        text_rotation_angledown,
        [Html("text_rotation_angleup")]
        text_rotation_angleup,
        [Html("text_rotation_down")]
        text_rotation_down,
        [Html("text_rotation_none")]
        text_rotation_none,
        [Html("theaters")]
        theaters,
        [Html("thumb_down")]
        thumb_down,
        [Html("thumb_up")]
        thumb_up,
        [Html("thumbs_up_down")]
        thumbs_up_down,
        [Html("timeline")]
        timeline,
        [Html("toc")]
        toc,
        [Html("today")]
        today,
        [Html("toll")]
        toll,
        [Html("touch_app")]
        touch_app,
        [Html("track_changes")]
        track_changes,
        [Html("translate")]
        translate,
        [Html("trending_down")]
        trending_down,
        [Html("trending_flat")]
        trending_flat,
        [Html("trending_up")]
        trending_up,
        [Html("turned_in")]
        turned_in,
        [Html("turned_in_not")]
        turned_in_not,
        [Html("update")]
        update,
        [Html("verified_user")]
        verified_user,
        [Html("vertical_split")]
        vertical_split,
        [Html("view_agenda")]
        view_agenda,
        [Html("view_array")]
        view_array,
        [Html("view_carousel")]
        view_carousel,
        [Html("view_column")]
        view_column,
        [Html("view_day")]
        view_day,
        [Html("view_headline")]
        view_headline,
        [Html("view_list")]
        view_list,
        [Html("view_module")]
        view_module,
        [Html("view_quilt")]
        view_quilt,
        [Html("view_stream")]
        view_stream,
        [Html("view_week")]
        view_week,
        [Html("visibility")]
        visibility,
        [Html("visibility_off")]
        visibility_off,
        [Html("voice_over_off")]
        voice_over_off,
        [Html("watch_later")]
        watch_later,
        [Html("work")]
        work,
        [Html("work_off")]
        work_off,
        [Html("work_outline")]
        work_outline,
        [Html("youtube_searched_for")]
        youtube_searched_for,
        [Html("zoom_in")]
        zoom_in,
        [Html("zoom_out")]
        zoom_out,

        //alert
        [Html("add_alert")]
        add_alert,
        [Html("error")]
        error,
        [Html("error_outline")]
        error_outline,
        [Html("notification_important")]
        notification_important,
        [Html("warning")]
        warning,

        //Av
        [Html("4k")]
        _4k,
        [Html("add_to_queue")]
        add_to_queue,
        [Html("airplay")]
        airplay,
        [Html("album")]
        album,
        [Html("art_track")]
        art_track,
        [Html("av_timer")]
        av_timer,
        [Html("branding_watermark")]
        branding_watermark,
        [Html("call_to_action")]
        call_to_action,
        [Html("closed_caption")]
        closed_caption,
        [Html("control_camera")]
        control_camera,
        [Html("equalizer")]
        equalizer,
        [Html("explicit")]
        _explicit,
        [Html("fast_forward")]
        fast_forward,
        [Html("fast_rewind")]
        fast_rewind,
        [Html("featured_play_list")]
        featured_play_list,
        [Html("featured_video")]
        featured_video,
        [Html("fiber_dvr")]
        fiber_dvr,
        [Html("fiber_manual_record")]
        fiber_manual_record,
        [Html("fiber_new")]
        fiber_new,
        [Html("fiber_pin")]
        fiber_pin,
        [Html("fiber_smart_record")]
        fiber_smart_record,
        [Html("forward_10")]
        forward_10,
        [Html("forward_30")]
        forward_30,
        [Html("forward_5")]
        forward_5,
        [Html("games")]
        games,
        [Html("hd")]
        hd,
        [Html("hearing")]
        hearing,
        [Html("high_quality")]
        high_quality,
        [Html("library_add")]
        library_add,
        [Html("library_books")]
        library_books,
        [Html("library_music")]
        library_music,
        [Html("loop")]
        loop,
        [Html("mic")]
        mic,
        [Html("mic_none")]
        mic_none,
        [Html("mic_off")]
        mic_off,
        [Html("missed_video_call")]
        missed_video_call,
        [Html("movie")]
        movie,
        [Html("music_video")]
        music_video,
        [Html("new_releases")]
        new_releases,
        [Html("not_interested")]
        not_interested,
        [Html("note")]
        note,
        [Html("pause")]
        pause,
        [Html("pause_circle_filled")]
        pause_circle_filled,
        [Html("pause_circle_outline")]
        pause_circle_outline,
        [Html("play_arrow")]
        play_arrow,
        [Html("play_circle_filled")]
        play_circle_filled,
        [Html("play_circle_outline")]
        play_circle_outline,
        [Html("playlist_add")]
        playlist_add,
        [Html("playlist_add_check")]
        playlist_add_check,
        [Html("playlist_play")]
        playlist_play,
        [Html("queue")]
        queue,
        [Html("queue_music")]
        queue_music,
        [Html("queue_play_next")]
        queue_play_next,
        [Html("radio")]
        radio,
        [Html("recent_actors")]
        recent_actors,
        [Html("remove_from_queue")]
        remove_from_queue,
        [Html("repeat")]
        repeat,
        [Html("repeat_one")]
        repeat_one,
        [Html("replay")]
        replay,
        [Html("replay_10")]
        replay_10,
        [Html("replay_30")]
        replay_30,
        [Html("replay_5")]
        replay_5,
        [Html("shuffle")]
        shuffle,
        [Html("skip_next")]
        skip_next,
        [Html("skip_previous")]
        skip_previous,
        [Html("slow_motion_video")]
        slow_motion_video,
        [Html("snooze")]
        snooze,
        [Html("sort_by_alpha")]
        sort_by_alpha,
        [Html("speed")]
        speed,
        [Html("stop")]
        stop,
        [Html("subscriptions")]
        subscriptions,
        [Html("subtitles")]
        subtitles,
        [Html("surround_sound")]
        surround_sound,
        [Html("video_call")]
        video_call,
        [Html("video_label")]
        video_label,
        [Html("video_library")]
        video_library,
        [Html("videocam")]
        videocam,
        [Html("videocam_off")]
        videocam_off,
        [Html("volume_down")]
        volume_down,
        [Html("volume_mute")]
        volume_mute,
        [Html("volume_off")]
        volume_off,
        [Html("volume_up")]
        volume_up,
        [Html("web")]
        web,
        [Html("web_asset")]
        web_asset,

        //communication
        [Html("business")]
        business,
        [Html("call")]
        call,
        [Html("call_end")]
        call_end,
        [Html("call_made")]
        call_made,
        [Html("call_merge")]
        call_merge,
        [Html("call_missed")]
        call_missed,
        [Html("call_missed_outgoing")]
        call_missed_outgoing,
        [Html("call_received")]
        call_received,
        [Html("call_split")]
        call_split,
        [Html("cancel_presentation")]
        cancel_presentation,
        [Html("chat")]
        chat,
        [Html("chat_bubble")]
        chat_bubble,
        [Html("chat_bubble_outline")]
        chat_bubble_outline,
        [Html("clear_all")]
        clear_all,
        [Html("comment")]
        comment,
        [Html("contact_mail")]
        contact_mail,
        [Html("contact_phone")]
        contact_phone,
        [Html("contacts")]
        contacts,
        [Html("desktop_access_disabled")]
        desktop_access_disabled,
        [Html("dialer_sip")]
        dialer_sip,
        [Html("dialpad")]
        dialpad,
        [Html("domain_disabled")]
        domain_disabled,
        [Html("duo")]
        duo,
        [Html("email")]
        email,
        [Html("forum")]
        forum,
        [Html("import_contacts")]
        import_contacts,
        [Html("import_export")]
        import_export,
        [Html("invert_colors_off")]
        invert_colors_off,
        [Html("list_alt")]
        list_alt,
        [Html("live_help")]
        live_help,
        [Html("mail_outline")]
        mail_outline,
        [Html("message")]
        message,
        [Html("mobile_screen_share")]
        mobile_screen_share,
        [Html("no_sim")]
        no_sim,
        [Html("pause_presentation")]
        pause_presentation,
        [Html("person_add_disabled")]
        person_add_disabled,
        [Html("phone")]
        phone,
        [Html("phone_disabled")]
        phone_disabled,
        [Html("phone_enabled")]
        phone_enabled,
        [Html("phonelink_erase")]
        phonelink_erase,
        [Html("phonelink_lock")]
        phonelink_lock,
        [Html("phonelink_ring")]
        phonelink_ring,
        [Html("phonelink_setup")]
        phonelink_setup,
        [Html("portable_wifi_off")]
        portable_wifi_off,
        [Html("present_to_all")]
        present_to_all,
        [Html("print_disabled")]
        print_disabled,
        [Html("ring_volume")]
        ring_volume,
        [Html("rss_feed")]
        rss_feed,
        [Html("screen_share")]
        screen_share,
        [Html("sentiment_satisfied_alt")]
        sentiment_satisfied_alt,
        [Html("speaker_phone")]
        speaker_phone,
        [Html("stay_current_landscape")]
        stay_current_landscape,
        [Html("stay_current_portrait")]
        stay_current_portrait,
        [Html("stay_primary_landscape")]
        stay_primary_landscape,
        [Html("stay_primary_portrait")]
        stay_primary_portrait,
        [Html("stop_screen_share")]
        stop_screen_share,
        [Html("swap_calls")]
        swap_calls,
        [Html("textsms")]
        textsms,
        [Html("unsubscribe")]
        unsubscribe,
        [Html("voicemail")]
        voicemail,
        [Html("vpn_key")]
        vpn_key,

        //content
        [Html("add")]
        add,
        [Html("add_box")]
        add_box,
        [Html("add_circle")]
        add_circle,
        [Html("add_circle_outline")]
        add_circle_outline,
        [Html("amp_stories")]
        amp_stories,
        [Html("archive")]
        archive,
        [Html("backspace")]
        backspace,
        [Html("ballot")]
        ballot,
        [Html("block")]
        block,
        [Html("clear")]
        clear,
        [Html("create")]
        create,
        [Html("delete_sweep")]
        delete_sweep,
        [Html("drafts")]
        drafts,
        [Html("dynamic_feed")]
        dynamic_feed,
        [Html("file_copy")]
        file_copy,
        [Html("filter_list")]
        filter_list,
        [Html("flag")]
        flag,
        [Html("font_download")]
        font_download,
        [Html("forward")]
        forward,
        [Html("gesture")]
        gesture,
        [Html("how_to_reg")]
        how_to_reg,
        [Html("how_to_vote")]
        how_to_vote,
        [Html("inbox")]
        inbox,
        [Html("link")]
        link,
        [Html("link_off")]
        link_off,
        [Html("low_priority")]
        low_priority,
        [Html("mail")]
        mail,
        [Html("markunread")]
        markunread,
        [Html("move_to_inbox")]
        move_to_inbox,
        [Html("next_week")]
        next_week,
        [Html("outlined_flag")]
        outlined_flag,
        [Html("policy")]
        policy,
        [Html("redo")]
        redo,
        [Html("remove")]
        remove,
        [Html("remove_circle")]
        remove_circle,
        [Html("remove_circle_outline")]
        remove_circle_outline,
        [Html("reply")]
        reply,
        [Html("reply_all")]
        reply_all,
        [Html("report")]
        report,
        [Html("report_off")]
        report_off,
        [Html("save")]
        save,
        [Html("save_alt")]
        save_alt,
        [Html("select_all")]
        select_all,
        [Html("send")]
        send,
        [Html("sort")]
        sort,
        [Html("square_foot")]
        square_foot,
        [Html("text_format")]
        text_format,
        [Html("unarchive")]
        unarchive,
        [Html("undo")]
        undo,
        [Html("waves")]
        waves,
        [Html("where_to_vote")]
        where_to_vote,

        //device
        [Html("access_alarm")]
        access_alarm,
        [Html("access_alarms")]
        access_alarms,
        [Html("access_time")]
        access_time,
        [Html("add_alarm")]
        add_alarm,
        [Html("add_to_home_screen")]
        add_to_home_screen,
        [Html("airplanemode_active")]
        airplanemode_active,
        [Html("airplanemode_inactive")]
        airplanemode_inactive,
        [Html("battery_alert")]
        battery_alert,
        [Html("battery_charging_full")]
        battery_charging_full,
        [Html("battery_full")]
        battery_full,
        [Html("battery_std")]
        battery_std,
        [Html("battery_unknown")]
        battery_unknown,
        [Html("bluetooth")]
        bluetooth,
        [Html("bluetooth_connected")]
        bluetooth_connected,
        [Html("bluetooth_disabled")]
        bluetooth_disabled,
        [Html("bluetooth_searching")]
        bluetooth_searching,
        [Html("brightness_auto")]
        brightness_auto,
        [Html("brightness_high")]
        brightness_high,
        [Html("brightness_low")]
        brightness_low,
        [Html("brightness_medium")]
        brightness_medium,
        [Html("data_usage")]
        data_usage,
        [Html("developer_mode")]
        developer_mode,
        [Html("devices")]
        devices,
        [Html("dvr")]
        dvr,
        [Html("gps_fixed")]
        gps_fixed,
        [Html("gps_not_fixed")]
        gps_not_fixed,
        [Html("gps_off")]
        gps_off,
        [Html("graphic_eq")]
        graphic_eq,
        [Html("location_disabled")]
        location_disabled,
        [Html("location_searching")]
        location_searching,
        [Html("mobile_friendly")]
        mobile_friendly,
        [Html("mobile_off")]
        mobile_off,
        [Html("nfc")]
        nfc,
        [Html("screen_lock_landscape")]
        screen_lock_landscape,
        [Html("screen_lock_portrait")]
        screen_lock_portrait,
        [Html("screen_lock_rotation")]
        screen_lock_rotation,
        [Html("screen_rotation")]
        screen_rotation,
        [Html("sd_storage")]
        sd_storage,
        [Html("settings_system_daydream")]
        settings_system_daydream,
        [Html("signal_cellular_4_bar")]
        signal_cellular_4_bar,
        [Html("signal_cellular_alt")]
        signal_cellular_alt,
        [Html("signal_cellular_connected_no_internet_4_bar")]
        signal_cellular_connected_no_internet_4_bar,
        [Html("signal_cellular_no_sim")]
        signal_cellular_no_sim,
        [Html("signal_cellular_null")]
        signal_cellular_null,
        [Html("signal_cellular_off")]
        signal_cellular_off,
        [Html("signal_wifi_4_bar")]
        signal_wifi_4_bar,
        [Html("signal_wifi_4_bar_lock")]
        signal_wifi_4_bar_lock,
        [Html("signal_wifi_off")]
        signal_wifi_off,
        [Html("storage")]
        storage,
        [Html("usb")]
        usb,
        [Html("wallpaper")]
        wallpaper,
        [Html("widgets")]
        widgets,
        [Html("wifi_lock")]
        wifi_lock,
        [Html("wifi_tethering")]
        wifi_tethering,

        //editor
        [Html("add_comment")]
        add_comment,
        [Html("attach_file")]
        attach_file,
        [Html("attach_money")]
        attach_money,
        [Html("bar_chart")]
        bar_chart,
        [Html("border_all")]
        border_all,
        [Html("border_bottom")]
        border_bottom,
        [Html("border_clear")]
        border_clear,
        [Html("border_horizontal")]
        border_horizontal,
        [Html("border_inner")]
        border_inner,
        [Html("border_left")]
        border_left,
        [Html("border_outer")]
        border_outer,
        [Html("border_right")]
        border_right,
        [Html("border_style")]
        border_style,
        [Html("border_top")]
        border_top,
        [Html("border_vertical")]
        border_vertical,
        [Html("bubble_chart")]
        bubble_chart,
        [Html("drag_handle")]
        drag_handle,
        [Html("format_align_center")]
        format_align_center,
        [Html("format_align_justify")]
        format_align_justify,
        [Html("format_align_left")]
        format_align_left,
        [Html("format_align_right")]
        format_align_right,
        [Html("format_bold")]
        format_bold,
        [Html("format_clear")]
        format_clear,
        [Html("format_color_reset")]
        format_color_reset,
        [Html("format_indent_decrease")]
        format_indent_decrease,
        [Html("format_indent_increase")]
        format_indent_increase,
        [Html("format_italic")]
        format_italic,
        [Html("format_line_spacing")]
        format_line_spacing,
        [Html("format_list_bulleted")]
        format_list_bulleted,
        [Html("format_list_numbered")]
        format_list_numbered,
        [Html("format_list_numbered_rtl")]
        format_list_numbered_rtl,
        [Html("format_paint")]
        format_paint,
        [Html("format_quote")]
        format_quote,
        [Html("format_shapes")]
        format_shapes,
        [Html("format_size")]
        format_size,
        [Html("format_strikethrough")]
        format_strikethrough,
        [Html("format_textdirection_l_to_r")]
        format_textdirection_l_to_r,
        [Html("format_textdirection_r_to_l")]
        format_textdirection_r_to_l,
        [Html("format_underlined")]
        format_underlined,
        [Html("functions")]
        functions,
        [Html("height")]
        height,
        [Html("highlight")]
        highlight,
        [Html("insert_chart")]
        insert_chart,
        [Html("insert_chart_outlined")]
        insert_chart_outlined,
        [Html("insert_comment")]
        insert_comment,
        [Html("insert_drive_file")]
        insert_drive_file,
        [Html("insert_emoticon")]
        insert_emoticon,
        [Html("insert_invitation")]
        insert_invitation,
        [Html("insert_link")]
        insert_link,
        [Html("insert_photo")]
        insert_photo,
        [Html("linear_scale")]
        linear_scale,
        [Html("merge_type")]
        merge_type,
        [Html("mode_comment")]
        mode_comment,
        [Html("monetization_on")]
        monetization_on,
        [Html("money_off")]
        money_off,
        [Html("multiline_chart")]
        multiline_chart,
        [Html("notes")]
        notes,
        [Html("pie_chart")]
        pie_chart,
        [Html("post_add")]
        post_add,
        [Html("publish")]
        publish,
        [Html("scatter_plot")]
        scatter_plot,
        [Html("score")]
        score,
        [Html("short_text")]
        short_text,
        [Html("show_chart")]
        show_chart,
        [Html("space_bar")]
        space_bar,
        [Html("strikethrough_s")]
        strikethrough_s,
        [Html("table_chart")]
        table_chart,
        [Html("text_fields")]
        text_fields,
        [Html("title")]
        title,
        [Html("vertical_align_bottom")]
        vertical_align_bottom,
        [Html("vertical_align_center")]
        vertical_align_center,
        [Html("vertical_align_top")]
        vertical_align_top,
        [Html("wrap_text")]
        wrap_text,

        //file
        [Html("attachment")]
        attachment,
        [Html("cloud")]
        cloud,
        [Html("cloud_circle")]
        cloud_circle,
        [Html("cloud_done")]
        cloud_done,
        [Html("cloud_download")]
        cloud_download,
        [Html("cloud_off")]
        cloud_off,
        [Html("cloud_queue")]
        cloud_queue,
        [Html("cloud_upload")]
        cloud_upload,
        [Html("create_new_folder")]
        create_new_folder,
        [Html("folder")]
        folder,
        [Html("folder_open")]
        folder_open,
        [Html("folder_shared")]
        folder_shared,

        //hardware
        [Html("cast")]
        cast,
        [Html("cast_connected")]
        cast_connected,
        [Html("computer")]
        computer,
        [Html("desktop_mac")]
        desktop_mac,
        [Html("desktop_windows")]
        desktop_windows,
        [Html("developer_board")]
        developer_board,
        [Html("device_hub")]
        device_hub,
        [Html("device_unknown")]
        device_unknown,
        [Html("devices_other")]
        devices_other,
        [Html("dock")]
        dock,
        [Html("gamepad")]
        gamepad,
        [Html("headset")]
        headset,
        [Html("headset_mic")]
        headset_mic,
        [Html("keyboard")]
        keyboard,
        [Html("keyboard_arrow_down")]
        keyboard_arrow_down,
        [Html("keyboard_arrow_left")]
        keyboard_arrow_left,
        [Html("keyboard_arrow_right")]
        keyboard_arrow_right,
        [Html("keyboard_arrow_up")]
        keyboard_arrow_up,
        [Html("keyboard_backspace")]
        keyboard_backspace,
        [Html("keyboard_capslock")]
        keyboard_capslock,
        [Html("keyboard_hide")]
        keyboard_hide,
        [Html("keyboard_return")]
        keyboard_return,
        [Html("keyboard_tab")]
        keyboard_tab,
        [Html("keyboard_voice")]
        keyboard_voice,
        [Html("laptop")]
        laptop,
        [Html("laptop_chromebook")]
        laptop_chromebook,
        [Html("laptop_mac")]
        laptop_mac,
        [Html("laptop_windows")]
        laptop_windows,
        [Html("memory")]
        memory,
        [Html("mouse")]
        mouse,
        [Html("phone_android")]
        phone_android,
        [Html("phone_iphone")]
        phone_iphone,
        [Html("phonelink")]
        phonelink,
        [Html("phonelink_off")]
        phonelink_off,
        [Html("power_input")]
        power_input,
        [Html("router")]
        router,
        [Html("scanner")]
        scanner,
        [Html("security")]
        security,
        [Html("sim_card")]
        sim_card,
        [Html("smartphone")]
        smartphone,
        [Html("speaker")]
        speaker,
        [Html("speaker_group")]
        speaker_group,
        [Html("tablet")]
        tablet,
        [Html("tablet_android")]
        tablet_android,
        [Html("tablet_mac")]
        tablet_mac,
        [Html("toys")]
        toys,
        [Html("tv")]
        tv,
        [Html("videogame_asset")]
        videogame_asset,
        [Html("watch")]
        watch,

        //image
        [Html("add_a_photo")]
        add_a_photo,
        [Html("add_photo_alternate")]
        add_photo_alternate,
        [Html("add_to_photos")]
        add_to_photos,
        [Html("adjust")]
        adjust,
        [Html("assistant")]
        assistant,
        [Html("assistant_photo")]
        assistant_photo,
        [Html("audiotrack")]
        audiotrack,
        [Html("blur_circular")]
        blur_circular,
        [Html("blur_linear")]
        blur_linear,
        [Html("blur_off")]
        blur_off,
        [Html("blur_on")]
        blur_on,
        [Html("brightness_1")]
        brightness_1,
        [Html("brightness_2")]
        brightness_2,
        [Html("brightness_3")]
        brightness_3,
        [Html("brightness_4")]
        brightness_4,
        [Html("brightness_5")]
        brightness_5,
        [Html("brightness_6")]
        brightness_6,
        [Html("brightness_7")]
        brightness_7,
        [Html("broken_image")]
        broken_image,
        [Html("brush")]
        brush,
        [Html("burst_mode")]
        burst_mode,
        [Html("camera")]
        camera,
        [Html("camera_alt")]
        camera_alt,
        [Html("camera_front")]
        camera_front,
        [Html("camera_rear")]
        camera_rear,
        [Html("camera_roll")]
        camera_roll,
        [Html("center_focus_strong")]
        center_focus_strong,
        [Html("center_focus_weak")]
        center_focus_weak,
        [Html("collections")]
        collections,
        [Html("collections_bookmark")]
        collections_bookmark,
        [Html("color_lens")]
        color_lens,
        [Html("colorize")]
        colorize,
        [Html("compare")]
        compare,
        [Html("control_point")]
        control_point,
        [Html("control_point_duplicate")]
        control_point_duplicate,
        [Html("crop")]
        crop,
        [Html("crop_16_9")]
        crop_16_9,
        [Html("crop_3_2")]
        crop_3_2,
        [Html("crop_5_4")]
        crop_5_4,
        [Html("crop_7_5")]
        crop_7_5,
        [Html("crop_din")]
        crop_din,
        [Html("crop_free")]
        crop_free,
        [Html("crop_landscape")]
        crop_landscape,
        [Html("crop_original")]
        crop_original,
        [Html("crop_portrait")]
        crop_portrait,
        [Html("crop_rotate")]
        crop_rotate,
        [Html("crop_square")]
        crop_square,
        [Html("dehaze")]
        dehaze,
        [Html("details")]
        details,
        [Html("edit")]
        edit,
        [Html("euro")]
        euro,
        [Html("exposure")]
        exposure,
        [Html("exposure_neg_1")]
        exposure_neg_1,
        [Html("exposure_neg_2")]
        exposure_neg_2,
        [Html("exposure_plus_1")]
        exposure_plus_1,
        [Html("exposure_plus_2")]
        exposure_plus_2,
        [Html("exposure_zero")]
        exposure_zero,
        [Html("filter")]
        filter,
        [Html("filter_1")]
        filter_1,
        [Html("filter_2")]
        filter_2,
        [Html("filter_3")]
        filter_3,
        [Html("filter_4")]
        filter_4,
        [Html("filter_5")]
        filter_5,
        [Html("filter_6")]
        filter_6,
        [Html("filter_7")]
        filter_7,
        [Html("filter_8")]
        filter_8,
        [Html("filter_9")]
        filter_9,
        [Html("filter_9_plus")]
        filter_9_plus,
        [Html("filter_b_and_w")]
        filter_b_and_w,
        [Html("filter_center_focus")]
        filter_center_focus,
        [Html("filter_drama")]
        filter_drama,
        [Html("filter_frames")]
        filter_frames,
        [Html("filter_hdr")]
        filter_hdr,
        [Html("filter_none")]
        filter_none,
        [Html("filter_tilt_shift")]
        filter_tilt_shift,
        [Html("filter_vintage")]
        filter_vintage,
        [Html("flare")]
        flare,
        [Html("flash_auto")]
        flash_auto,
        [Html("flash_off")]
        flash_off,
        [Html("flash_on")]
        flash_on,
        [Html("flip")]
        flip,
        [Html("flip_camera_android")]
        flip_camera_android,
        [Html("flip_camera_ios")]
        flip_camera_ios,
        [Html("gradient")]
        gradient,
        [Html("grain")]
        grain,
        [Html("grid_off")]
        grid_off,
        [Html("grid_on")]
        grid_on,
        [Html("hdr_off")]
        hdr_off,
        [Html("hdr_on")]
        hdr_on,
        [Html("hdr_strong")]
        hdr_strong,
        [Html("hdr_weak")]
        hdr_weak,
        [Html("healing")]
        healing,
        [Html("image")]
        image,
        [Html("image_aspect_ratio")]
        image_aspect_ratio,
        [Html("image_search")]
        image_search,
        [Html("iso")]
        iso,
        [Html("landscape")]
        landscape,
        [Html("leak_add")]
        leak_add,
        [Html("leak_remove")]
        leak_remove,
        [Html("lens")]
        lens,
        [Html("linked_camera")]
        linked_camera,
        [Html("looks")]
        looks,
        [Html("looks_3")]
        looks_3,
        [Html("looks_4")]
        looks_4,
        [Html("looks_5")]
        looks_5,
        [Html("looks_6")]
        looks_6,
        [Html("looks_one")]
        looks_one,
        [Html("looks_two")]
        looks_two,
        [Html("loupe")]
        loupe,
        [Html("monochrome_photos")]
        monochrome_photos,
        [Html("movie_creation")]
        movie_creation,
        [Html("movie_filter")]
        movie_filter,
        [Html("music_note")]
        music_note,
        [Html("music_off")]
        music_off,
        [Html("nature")]
        nature,
        [Html("nature_people")]
        nature_people,
        [Html("navigate_before")]
        navigate_before,
        [Html("navigate_next")]
        navigate_next,
        [Html("palette")]
        palette,
        [Html("panorama")]
        panorama,
        [Html("panorama_fish_eye")]
        panorama_fish_eye,
        [Html("panorama_horizontal")]
        panorama_horizontal,
        [Html("panorama_vertical")]
        panorama_vertical,
        [Html("panorama_wide_angle")]
        panorama_wide_angle,
        [Html("photo")]
        photo,
        [Html("photo_album")]
        photo_album,
        [Html("photo_camera")]
        photo_camera,
        [Html("photo_filter")]
        photo_filter,
        [Html("photo_library")]
        photo_library,
        [Html("photo_size_select_actual")]
        photo_size_select_actual,
        [Html("photo_size_select_large")]
        photo_size_select_large,
        [Html("photo_size_select_small")]
        photo_size_select_small,
        [Html("picture_as_pdf")]
        picture_as_pdf,
        [Html("portrait")]
        portrait,
        [Html("remove_red_eye")]
        remove_red_eye,
        [Html("rotate_90_degrees_ccw")]
        rotate_90_degrees_ccw,
        [Html("rotate_left")]
        rotate_left,
        [Html("rotate_right")]
        rotate_right,
        [Html("shutter_speed")]
        shutter_speed,
        [Html("slideshow")]
        slideshow,
        [Html("straighten")]
        straighten,
        [Html("style")]
        style,
        [Html("switch_camera")]
        switch_camera,
        [Html("switch_video")]
        switch_video,
        [Html("tag_faces")]
        tag_faces,
        [Html("texture")]
        texture,
        [Html("timelapse")]
        timelapse,
        [Html("timer")]
        timer,
        [Html("timer_10")]
        timer_10,
        [Html("timer_3")]
        timer_3,
        [Html("timer_off")]
        timer_off,
        [Html("tonality")]
        tonality,
        [Html("transform")]
        transform,
        [Html("tune")]
        tune,
        [Html("view_comfy")]
        view_comfy,
        [Html("view_compact")]
        view_compact,
        [Html("vignette")]
        vignette,
        [Html("wb_auto")]
        wb_auto,
        [Html("wb_cloudy")]
        wb_cloudy,
        [Html("wb_incandescent")]
        wb_incandescent,
        [Html("wb_iridescent")]
        wb_iridescent,
        [Html("wb_sunny")]
        wb_sunny,

        //maps
        [Html("360")]
        _360,
        [Html("atm")]
        atm,
        [Html("beenhere")]
        beenhere,
        [Html("category")]
        category,
        [Html("compass_calibration")]
        compass_calibration,
        [Html("departure_board")]
        departure_board,
        [Html("directions")]
        directions,
        [Html("directions_bike")]
        directions_bike,
        [Html("directions_boat")]
        directions_boat,
        [Html("directions_bus")]
        directions_bus,
        [Html("directions_car")]
        directions_car,
        [Html("directions_railway")]
        directions_railway,
        [Html("directions_run")]
        directions_run,
        [Html("directions_subway")]
        directions_subway,
        [Html("directions_transit")]
        directions_transit,
        [Html("directions_walk")]
        directions_walk,
        [Html("edit_attributes")]
        edit_attributes,
        [Html("ev_station")]
        ev_station,
        [Html("fastfood")]
        fastfood,
        [Html("flight")]
        flight,
        [Html("hotel")]
        hotel,
        [Html("layers")]
        layers,
        [Html("layers_clear")]
        layers_clear,
        [Html("local_activity")]
        local_activity,
        [Html("local_airport")]
        local_airport,
        [Html("local_atm")]
        local_atm,
        [Html("local_bar")]
        local_bar,
        [Html("local_cafe")]
        local_cafe,
        [Html("local_car_wash")]
        local_car_wash,
        [Html("local_convenience_store")]
        local_convenience_store,
        [Html("local_dining")]
        local_dining,
        [Html("local_drink")]
        local_drink,
        [Html("local_florist")]
        local_florist,
        [Html("local_gas_station")]
        local_gas_station,
        [Html("local_grocery_store")]
        local_grocery_store,
        [Html("local_hospital")]
        local_hospital,
        [Html("local_hotel")]
        local_hotel,
        [Html("local_laundry_service")]
        local_laundry_service,
        [Html("local_library")]
        local_library,
        [Html("local_mall")]
        local_mall,
        [Html("local_movies")]
        local_movies,
        [Html("local_offer")]
        local_offer,
        [Html("local_parking")]
        local_parking,
        [Html("local_pharmacy")]
        local_pharmacy,
        [Html("local_phone")]
        local_phone,
        [Html("local_pizza")]
        local_pizza,
        [Html("local_play")]
        local_play,
        [Html("local_post_office")]
        local_post_office,
        [Html("local_printshop")]
        local_printshop,
        [Html("local_see")]
        local_see,
        [Html("local_shipping")]
        local_shipping,
        [Html("local_taxi")]
        local_taxi,
        [Html("map")]
        map,
        [Html("menu_book")]
        menu_book,
        [Html("money")]
        money,
        [Html("museum")]
        museum,
        [Html("my_location")]
        my_location,
        [Html("navigation")]
        navigation,
        [Html("near_me")]
        near_me,
        [Html("person_pin")]
        person_pin,
        [Html("rate_review")]
        rate_review,
        [Html("restaurant")]
        restaurant,
        [Html("restaurant_menu")]
        restaurant_menu,
        [Html("satellite")]
        satellite,
        [Html("store_mall_directory")]
        store_mall_directory,
        [Html("streetview")]
        streetview,
        [Html("subway")]
        subway,
        [Html("terrain")]
        terrain,
        [Html("traffic")]
        traffic,
        [Html("train")]
        train,
        [Html("tram")]
        tram,
        [Html("transfer_within_a_station")]
        transfer_within_a_station,
        [Html("transit_enterexit")]
        transit_enterexit,
        [Html("trip_origin")]
        trip_origin,
        [Html("zoom_out_map")]
        zoom_out_map,

        //navigation
        [Html("apps")]
        apps,
        [Html("arrow_back")]
        arrow_back,
        [Html("arrow_back_ios")]
        arrow_back_ios,
        [Html("arrow_downward")]
        arrow_downward,
        [Html("arrow_drop_down")]
        arrow_drop_down,
        [Html("arrow_drop_down_circle")]
        arrow_drop_down_circle,
        [Html("arrow_drop_up")]
        arrow_drop_up,
        [Html("arrow_forward")]
        arrow_forward,
        [Html("arrow_forward_ios")]
        arrow_forward_ios,
        [Html("arrow_left")]
        arrow_left,
        [Html("arrow_right")]
        arrow_right,
        [Html("arrow_upward")]
        arrow_upward,
        [Html("cancel")]
        cancel,
        [Html("check")]
        check,
        [Html("chevron_left")]
        chevron_left,
        [Html("chevron_right")]
        chevron_right,
        [Html("close")]
        close,
        [Html("double_arrow")]
        double_arrow,
        [Html("expand_less")]
        expand_less,
        [Html("expand_more")]
        expand_more,
        [Html("first_page")]
        first_page,
        [Html("fullscreen")]
        fullscreen,
        [Html("fullscreen_exit")]
        fullscreen_exit,
        [Html("home_work")]
        home_work,
        [Html("last_page")]
        last_page,
        [Html("menu")]
        menu,
        [Html("menu_open")]
        menu_open,
        [Html("more_horiz")]
        more_horiz,
        [Html("more_vert")]
        more_vert,
        [Html("refresh")]
        refresh,
        [Html("subdirectory_arrow_left")]
        subdirectory_arrow_left,
        [Html("subdirectory_arrow_right")]
        subdirectory_arrow_right,
        [Html("unfold_less")]
        unfold_less,
        [Html("unfold_more")]
        unfold_more,

        //notification
        [Html("account_tree")]
        account_tree,
        [Html("adb")]
        adb,
        [Html("airline_seat_flat")]
        airline_seat_flat,
        [Html("airline_seat_flat_angled")]
        airline_seat_flat_angled,
        [Html("airline_seat_individual_suite")]
        airline_seat_individual_suite,
        [Html("airline_seat_legroom_extra")]
        airline_seat_legroom_extra,
        [Html("airline_seat_legroom_normal")]
        airline_seat_legroom_normal,
        [Html("airline_seat_legroom_reduced")]
        airline_seat_legroom_reduced,
        [Html("airline_seat_recline_extra")]
        airline_seat_recline_extra,
        [Html("airline_seat_recline_normal")]
        airline_seat_recline_normal,
        [Html("bluetooth_audio")]
        bluetooth_audio,
        [Html("confirmation_number")]
        confirmation_number,
        [Html("disc_full")]
        disc_full,
        [Html("drive_eta")]
        drive_eta,
        [Html("enhanced_encryption")]
        enhanced_encryption,
        [Html("event_available")]
        event_available,
        [Html("event_busy")]
        event_busy,
        [Html("event_note")]
        event_note,
        [Html("folder_special")]
        folder_special,
        [Html("live_tv")]
        live_tv,
        [Html("mms")]
        mms,
        [Html("more")]
        more,
        [Html("network_check")]
        network_check,
        [Html("network_locked")]
        network_locked,
        [Html("no_encryption")]
        no_encryption,
        [Html("ondemand_video")]
        ondemand_video,
        [Html("personal_video")]
        personal_video,
        [Html("phone_bluetooth_speaker")]
        phone_bluetooth_speaker,
        [Html("phone_callback")]
        phone_callback,
        [Html("phone_forwarded")]
        phone_forwarded,
        [Html("phone_in_talk")]
        phone_in_talk,
        [Html("phone_locked")]
        phone_locked,
        [Html("phone_missed")]
        phone_missed,
        [Html("phone_paused")]
        phone_paused,
        [Html("power")]
        power,
        [Html("power_off")]
        power_off,
        [Html("priority_high")]
        priority_high,
        [Html("sd_card")]
        sd_card,
        [Html("sms")]
        sms,
        [Html("sms_failed")]
        sms_failed,
        [Html("sync")]
        sync,
        [Html("sync_disabled")]
        sync_disabled,
        [Html("sync_problem")]
        sync_problem,
        [Html("system_update")]
        system_update,
        [Html("tap_and_play")]
        tap_and_play,
        [Html("time_to_leave")]
        time_to_leave,
        [Html("tv_off")]
        tv_off,
        [Html("vibration")]
        vibration,
        [Html("voice_chat")]
        voice_chat,
        [Html("vpn_lock")]
        vpn_lock,
        [Html("wc")]
        wc,
        [Html("wifi")]
        wifi,
        [Html("wifi_off")]
        wifi_off,

        //places
        [Html("ac_unit")]
        ac_unit,
        [Html("airport_shuttle")]
        airport_shuttle,
        [Html("all_inclusive")]
        all_inclusive,
        [Html("apartment")]
        apartment,
        [Html("bathtub")]
        bathtub,
        [Html("beach_access")]
        beach_access,
        [Html("business_center")]
        business_center,
        [Html("casino")]
        casino,
        [Html("child_care")]
        child_care,
        [Html("child_friendly")]
        child_friendly,
        [Html("fitness_center")]
        fitness_center,
        [Html("free_breakfast")]
        free_breakfast,
        [Html("golf_course")]
        golf_course,
        [Html("hot_tub")]
        hot_tub,
        [Html("house")]
        house,
        [Html("kitchen")]
        kitchen,
        [Html("meeting_room")]
        meeting_room,
        [Html("no_meeting_room")]
        no_meeting_room,
        [Html("pool")]
        pool,
        [Html("room_service")]
        room_service,
        [Html("rv_hookup")]
        rv_hookup,
        [Html("smoke_free")]
        smoke_free,
        [Html("smoking_rooms")]
        smoking_rooms,
        [Html("spa")]
        spa,
        [Html("storefront")]
        storefront,

        //social
        [Html("cake")]
        cake,
        [Html("deck")]
        deck,
        [Html("emoji_emotions")]
        emoji_emotions,
        [Html("emoji_events")]
        emoji_events,
        [Html("emoji_flags")]
        emoji_flags,
        [Html("emoji_food_beverage")]
        emoji_food_beverage,
        [Html("emoji_nature")]
        emoji_nature,
        [Html("emoji_objects")]
        emoji_objects,
        [Html("emoji_people")]
        emoji_people,
        [Html("emoji_symbols")]
        emoji_symbols,
        [Html("emoji_transportation")]
        emoji_transportation,
        [Html("fireplace")]
        fireplace,
        [Html("group")]
        group,
        [Html("group_add")]
        group_add,
        [Html("king_bed")]
        king_bed,
        [Html("location_city")]
        location_city,
        [Html("mood")]
        mood,
        [Html("mood_bad")]
        mood_bad,
        [Html("nights_stay")]
        nights_stay,
        [Html("notifications")]
        notifications,
        [Html("notifications_active")]
        notifications_active,
        [Html("notifications_none")]
        notifications_none,
        [Html("notifications_off")]
        notifications_off,
        [Html("notifications_paused")]
        notifications_paused,
        [Html("outdoor_grill")]
        outdoor_grill,
        [Html("pages")]
        pages,
        [Html("party_mode")]
        party_mode,
        [Html("people")]
        people,
        [Html("people_alt")]
        people_alt,
        [Html("people_outline")]
        people_outline,
        [Html("person")]
        person,
        [Html("person_add")]
        person_add,
        [Html("person_outline")]
        person_outline,
        [Html("plus_one")]
        plus_one,
        [Html("poll")]
        poll,
        [Html("public")]
        _public,
        [Html("school")]
        school,
        [Html("sentiment_dissatisfied")]
        sentiment_dissatisfied,
        [Html("sentiment_satisfied")]
        sentiment_satisfied,
        [Html("sentiment_very_dissatisfied")]
        sentiment_very_dissatisfied,
        [Html("sentiment_very_satisfied")]
        sentiment_very_satisfied,
        [Html("share")]
        share,
        [Html("single_bed")]
        single_bed,
        [Html("sports")]
        sports,
        [Html("sports_baseball")]
        sports_baseball,
        [Html("sports_basketball")]
        sports_basketball,
        [Html("sports_cricket")]
        sports_cricket,
        [Html("sports_esports")]
        sports_esports,
        [Html("sports_football")]
        sports_football,
        [Html("sports_golf")]
        sports_golf,
        [Html("sports_handball")]
        sports_handball,
        [Html("sports_hockey")]
        sports_hockey,
        [Html("sports_kabaddi")]
        sports_kabaddi,
        [Html("sports_mma")]
        sports_mma,
        [Html("sports_motorsports")]
        sports_motorsports,
        [Html("sports_rugby")]
        sports_rugby,
        [Html("sports_soccer")]
        sports_soccer,
        [Html("sports_tennis")]
        sports_tennis,
        [Html("sports_volleyball")]
        sports_volleyball,
        [Html("thumb_down_alt")]
        thumb_down_alt,
        [Html("thumb_up_alt")]
        thumb_up_alt,
        [Html("whatshot")]
        whatshot,

        //toogle
        [Html("check_box")]
        check_box,
        [Html("check_box_outline_blank")]
        check_box_outline_blank,
        [Html("indeterminate_check_box")]
        indeterminate_check_box,
        [Html("radio_button_checked")]
        radio_button_checked,
        [Html("radio_button_unchecked")]
        radio_button_unchecked,
        [Html("star")]
        star,
        [Html("star_border")]
        star_border,
        [Html("star_half")]
        star_half,
        [Html("toggle_off")]
        toggle_off,
        [Html("toggle_on")]
        toggle_on,


        //uncategorized
        [Html("format_color_fill")]
        format_color_fill,
        [Html("format_color_text")]
        format_color_text,
        [Html("border_color")]
        border_color,
        [Html("sentiment_neutral")]
        sentiment_neutral,
        [Html("add_location")]
        add_location,
        [Html("file_download")]
        file_download,
        [Html("content_copy")]
        content_copy,
        [Html("content_cut")]
        content_cut,
        [Html("content_paste")]
        content_paste,
        [Html("do_not_disturb")]
        do_not_disturb,
        [Html("do_not_disturb_alt")]
        do_not_disturb_alt,
        [Html("do_not_disturb_off")]
        do_not_disturb_off,
        [Html("do_not_disturb_on")]
        do_not_disturb_on,
        [Html("domain")]
        domain,
        [Html("edit_location")]
        edit_location,
        [Html("file_upload")]
        file_upload,
        [Html("info_outline")]
        info_outline,
        [Html("label_outline")]
        label_outline,
        [Html("lightbulb_outline")]
        lightbulb_outline,
        [Html("location_off")]
        location_off,
        [Html("location_on")]
        location_on,
        [Html("lock_outline")]
        lock_outline,
        [Html("mode_edit")]
        mode_edit,
        [Html("network_cell")]
        network_cell,
        [Html("network_wifi")]
        network_wifi,
        [Html("person_pin_circle")]
        person_pin_circle,
        [Html("pie_chart_outlined")]
        pie_chart_outlined,
        [Html("pin_drop")]
        pin_drop,
        [Html("place")]
        place,
        [Html("settings")]
        settings,
        [Html("sim_card_alert")]
        sim_card_alert,
        [Html("weekend")]
        weekend,
    }
}